// ------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY SEMANTIC-RELEASE.
// DO NOT EDIT MANUALLY.
// ------------------------------------------------------------

export interface VersionInfo {
  version: string;
  releaseDate: string;
}

export const versionInfo: VersionInfo = {
  version: '2.0.6',
  releaseDate: '2025-11-11T16:46:37Z',
};
