// ------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY SEMANTIC-RELEASE.
// DO NOT EDIT MANUALLY.
// ------------------------------------------------------------

export interface VersionInfo {
  version: string;
  releaseDate: string;
}

export const versionInfo: VersionInfo = {
  version: '2.13.0',
  releaseDate: '2025-12-07T17:02:23Z',
};
