// ------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY SEMANTIC-RELEASE.
// DO NOT EDIT MANUALLY.
// ------------------------------------------------------------

export interface VersionInfo {
  version: string;
  releaseDate: string;
}

export const versionInfo: VersionInfo = {
  version: '0.0.0',
  releaseDate: '1970-01-01T00:00:00Z',
};
